# Generated by Django 6.0.6 on 2026-07-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_summer_sale',
            field=models.BooleanField(default=False, verbose_name='آیا در سامرتخفیف است؟'),
        ),
    ]
