# Generated by Django 6.0.6 on 2026-07-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_summer_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='لینک عکس دسته\u200cبندی'),
        ),
    ]
