# Generated by Django 6.0.6 on 2026-07-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10, verbose_name='موجودی انبار'),
        ),
    ]
