# Generated by Django 6.0.6 on 2026-07-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_first_purchase_only',
            field=models.BooleanField(default=False, verbose_name='فقط برای اولین خرید'),
        ),
    ]
