# Generated by Django 6.0.6 on 2026-07-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_coupon_is_first_purchase_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('short_desc', models.CharField(max_length=300, verbose_name='خلاصه کوتاه')),
                ('body', models.TextField(verbose_name='متن کامل مقاله')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='لینک عکس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
            ],
        ),
    ]
