# Generated by Django 6.0.6 on 2026-08-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_review_admin_reply_review_dislikes_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف (0 تا 100)'),
        ),
    ]
