# Generated by Django 6.0.6 on 2026-08-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='آدرس عکس'),
        ),
    ]
